plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.focusalert'
version = '0.1.0'

android {
  namespace "expo.modules.focusalert"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}
dependencies {
  // Native module dependency for receiving focus alert push messages.
  implementation platform('com.google.firebase:firebase-bom:34.3.0')
  implementation 'com.google.firebase:firebase-messaging'
}